USE chess_society_db;

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_officer BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE event(
      id INTEGER PRIMARY KEY AUTO_INCREMENT,
      name VARCHAR(255) NOT NULL,
      description TEXT NOT NULL,
      time DATETIME NOT NULL,
      location VARCHAR(255) NOT NULL,
      available_from DATETIME,
      expires DATETIME
);

INSERT into event(name, event.description, time, available_from, location, expires) VALUES ('Meet and greet', 'Small meet and greet for society members',
                                                                            '2019-12-05 14:29:36','1999-12-05 14:29:36', 'House', '2020-11-05 14:29:36');


INSERT INTO users(username, password, is_officer)
VALUES ('michael','123456',TRUE);

CREATE TABLE MEMBER (
    MEMBER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    MEMBER_ADDRESS VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(11) NOT NULL,
    GENDER VARCHAR(15) NOT NULL,
    DOB DATE NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);

CREATE TABLE OFFICER (
    OFFICER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    OFFICER_ADDRESS VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(11) NOT NULL,
    GENDER VARCHAR(15) NOT NULL,
    DOB DATE NOT NULL,
    PRIMARY KEY (OFFICER_ID)
);


CREATE TABLE NEWS (
    INFO VARCHAR (500) NOT NULL,
    THERELEASE DATETIME NOT NULL,
    EXPIRY DATETIME NOT NULL,
    NEWS_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (NEWS_ID)
);

CREATE TABLE EVENTS (
    NAME VARCHAR(255) NOT NULL,
    TIME DATETIME NOT NULL,
    INFO VARCHAR (500) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    THERELEASE DATETIME NOT NULL,
    EXPIRY DATETIME NOT NULL,
    EVENTS_ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (EVENTS_ID)
);

CREATE TABLE TOURNAMENT (
    NAME VARCHAR(255) NOT NULL,
    INFO VARCHAR (500) NOT NULL,
    SIGNUP_DEADLINE DATETIME NOT NULL,
    TOURNAMENT_ID INT NOT NULL AUTO_INCREMENT,
    ORGANIZER_ID INT NOT NULL,
    PRIMARY KEY (TOURNAMENT_ID),
    FOREIGN KEY (ORGANIZER_ID) REFERENCES OFFICER(OFFICER_ID) ON DELETE CASCADE
);

CREATE TABLE TOURNAMENT_CO_ORGANIZER(
    TOURNAMENT_ID INT NOT NULL,
    CO_ORGANIZER_ID INT NOT NULL,
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (CO_ORGANIZER_ID) REFERENCES OFFICER(OFFICER_ID)
);

CREATE TABLE TOURNAMENT_PARTICIPANT (
                                    TOURNAMENT_ID INT NOT NULL,
                                    PARTICIPANT_ID INT NOT NULL,
                                    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID),
                                    FOREIGN KEY (PARTICIPANT_ID) REFERENCES MEMBER(MEMBER_ID)
);

INSERT INTO NEWS(INFO, THERELEASE, EXPIRY) VALUES ('Magnus Carlsen increased his lead even more at the Tata Steel Chess India Rapid & Blitz.',
                                                                            '2015-11-05 12:10', '2020-10-17 13:30');

CREATE TABLE MATCHS(
    MATCHS_ID INT NOT NULL AUTO_INCREMENT,
    TOURNAMENT_ID INT NOT NULL,
    PRIMARY KEY (MATCHS_ID),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TOURNAMENT_ID)
);


CREATE TABLE MATCHS_PARTICIPANT (
    MATCHS_ID INT NOT NULL,
    PARTICIPANT_ID INT NOT NULL,
    SCORE INT NOT NULL,
    FOREIGN KEY (MATCHS_ID) REFERENCES MATCHS(MATCHS_ID),
    FOREIGN KEY (PARTICIPANT_ID) REFERENCES MEMBER(MEMBER_ID)
);